"""add invited_by_user_ids to external_guests

Revision ID: eae67b2e1678
Revises: 434157c97635
Create Date: 2025-12-15 14:24:46.011913+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eae67b2e1678'
down_revision: Union[str, None] = '434157c97635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_guests', sa.Column('invited_by_user_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='邀请人用户ID列表'))
    op.alter_column('external_guests', 'invited_by_user_id',
               existing_type=sa.BIGINT(),
               comment='主要邀请人（向后兼容）',
               existing_comment='谁邀请的',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('external_guests', 'invited_by_user_id',
               existing_type=sa.BIGINT(),
               comment='谁邀请的',
               existing_comment='主要邀请人（向后兼容）',
               existing_nullable=True)
    op.drop_column('external_guests', 'invited_by_user_ids')
    # ### end Alembic commands ###

