"""add_attachments_to_posts

Revision ID: f84f057b642c
Revises: 5e53948d724d
Create Date: 2025-12-15 11:50:21.025747+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f84f057b642c'
down_revision: Union[str, None] = '5e53948d724d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='附件列表 [{name, url, type, size}]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'attachments')
    # ### end Alembic commands ###

