"""add_project_invitations_table

Revision ID: 9f08395fa617
Revises: a0725a055e65
Create Date: 2025-12-15 05:22:29.067951+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f08395fa617'
down_revision: Union[str, None] = 'a0725a055e65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 使用原生SQL创建表，避免枚举类型冲突
    # 创建枚举类型（如果不存在）
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE invitation_status AS ENUM ('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    
    op.execute("""
        CREATE TABLE project_invitations (
            id BIGSERIAL PRIMARY KEY,
            project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
            inviter_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            invitee_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            proposed_role project_member_role NOT NULL DEFAULT 'MEMBER',
            proposed_duty TEXT,
            proposed_share_pct NUMERIC(10, 4),
            message TEXT,
            status invitation_status NOT NULL DEFAULT 'PENDING',
            responded_at TIMESTAMPTZ,
            response_note TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            is_deleted BOOLEAN NOT NULL DEFAULT FALSE
        );
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_invitations')
    # ### end Alembic commands ###

