"""add_attachments_and_reference_to_dm_messages

Revision ID: 434157c97635
Revises: f84f057b642c
Create Date: 2025-12-15 13:00:06.904917+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '434157c97635'
down_revision: Union[str, None] = 'f84f057b642c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dm_messages', sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='附件列表'))
    op.add_column('dm_messages', sa.Column('reference_type', sa.String(length=20), nullable=True, comment='引用类型: project/resource'))
    op.add_column('dm_messages', sa.Column('reference_id', sa.BigInteger(), nullable=True, comment='引用的项目/资源ID'))
    op.add_column('dm_messages', sa.Column('reference_name', sa.String(length=255), nullable=True, comment='引用的项目/资源名称'))
    op.alter_column('dm_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dm_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('dm_messages', 'reference_name')
    op.drop_column('dm_messages', 'reference_id')
    op.drop_column('dm_messages', 'reference_type')
    op.drop_column('dm_messages', 'attachments')
    # ### end Alembic commands ###

