"""add_all_schema_v2_tables

Revision ID: a0725a055e65
Revises: 
Create Date: 2025-12-14 11:03:13.431534+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0725a055e65'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_sources',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='源名称'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='类型: RSS/HTML/API'),
    sa.Column('base_url', sa.String(length=500), nullable=False, comment='基础URL'),
    sa.Column('fetch_frequency_minutes', sa.Integer(), nullable=False, comment='抓取频率（分钟）'),
    sa.Column('parse_rule', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='解析规则配置'),
    sa.Column('default_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='默认标签数组'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='标签名'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='角色名称'),
    sa.Column('code', sa.String(length=20), nullable=False, comment='角色代码: FOUNDING/CORE/NORMAL'),
    sa.Column('role_level', sa.Integer(), nullable=False, comment='角色层级: 3=联合创始人, 2=核心, 1=普通'),
    sa.Column('is_system', sa.Boolean(), nullable=True, comment='是否系统角色'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='姓名'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='邮箱'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='头像URL'),
    sa.Column('organization', sa.String(length=255), nullable=True, comment='所属组织'),
    sa.Column('organization_public', sa.Boolean(), nullable=True, comment='组织是否公开'),
    sa.Column('title', sa.String(length=100), nullable=True, comment='职务头衔'),
    sa.Column('gender', sa.String(length=10), nullable=True, comment='性别: MALE/FEMALE/OTHER'),
    sa.Column('birth_date', sa.Date(), nullable=True, comment='出生日期'),
    sa.Column('intro', sa.Text(), nullable=True, comment='自我描述'),
    sa.Column('expertise', sa.Text(), nullable=True, comment='擅长领域'),
    sa.Column('contact', sa.String(length=255), nullable=True, comment='联系方式'),
    sa.Column('contact_public', sa.Boolean(), nullable=True, comment='联系方式是否公开'),
    sa.Column('address', sa.String(length=500), nullable=True, comment='地址'),
    sa.Column('address_public', sa.Boolean(), nullable=True, comment='地址是否公开'),
    sa.Column('education', sa.Text(), nullable=True, comment='教育经历'),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='公开标签数组'),
    sa.Column('hobbies', sa.Text(), nullable=True, comment='爱好'),
    sa.Column('signature', sa.Text(), nullable=True, comment='个性签名'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='加密密码'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否有效'),
    sa.Column('is_admin', sa.Boolean(), nullable=True, comment='是否管理员'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('announcements',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='公告名称'),
    sa.Column('content', sa.Text(), nullable=False, comment='公告内容'),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='附件列表'),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('visibility_scope_type', sa.Enum('ALL', 'ROLE_MIN_LEVEL', 'CUSTOM', name='visibility_scope_type'), nullable=False),
    sa.Column('visibility_min_role_level', sa.Integer(), nullable=True),
    sa.Column('visibility_user_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='操作人'),
    sa.Column('action', sa.String(length=100), nullable=False, comment='操作类型'),
    sa.Column('object_type', sa.String(length=50), nullable=False, comment='对象类型'),
    sa.Column('object_id', sa.BigInteger(), nullable=False, comment='对象ID'),
    sa.Column('summary', sa.Text(), nullable=False, comment='简要说明'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_object_type'), 'audit_logs', ['object_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('dm_threads',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_a_id', sa.BigInteger(), nullable=False),
    sa.Column('user_b_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_a_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_b_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedbacks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='反馈人'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='类别: PRODUCT/BUG/POLICY/OTHER'),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('contact', sa.String(length=200), nullable=True, comment='联系方式'),
    sa.Column('allow_contact', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', 'REJECTED', name='feedback_status'), nullable=False),
    sa.Column('admin_reply', sa.Text(), nullable=True, comment='管理员回复'),
    sa.Column('admin_user_id', sa.BigInteger(), nullable=True),
    sa.Column('admin_replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inbox_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.Enum('ANNOUNCEMENT', 'SYSTEM', 'VOTE', 'DM', 'MENTION', name='inbox_category'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=True, comment='消息内容摘要/全文'),
    sa.Column('related_object_type', sa.String(length=50), nullable=True, comment='PROJECT/DEMAND/TRANSACTION/VOTE/MEETING/POST/COMMENT/ANNOUNCEMENT/DM_THREAD'),
    sa.Column('related_object_id', sa.BigInteger(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbox_items_is_read'), 'inbox_items', ['is_read'], unique=False)
    op.create_index(op.f('ix_inbox_items_user_id'), 'inbox_items', ['user_id'], unique=False)
    op.create_table('news',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False, comment='新闻标题'),
    sa.Column('summary', sa.Text(), nullable=True, comment='摘要'),
    sa.Column('source_name', sa.String(length=100), nullable=True, comment='来源名称'),
    sa.Column('original_url', sa.String(length=1000), nullable=False, comment='原文URL'),
    sa.Column('publish_time', sa.DateTime(timezone=True), nullable=True, comment='发布时间'),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True, comment='抓取时间'),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='标签数组'),
    sa.Column('added_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('original_url')
    )
    op.create_table('projects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='项目名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='项目描述'),
    sa.Column('business_type', sa.String(length=50), nullable=False, comment='业务类型: 协议转让/并购重组/产业赋能/债权业务/其他'),
    sa.Column('industry', sa.String(length=100), nullable=True, comment='行业'),
    sa.Column('region', sa.String(length=100), nullable=True, comment='地区'),
    sa.Column('review_status', sa.Enum('PENDING_REVIEW', 'APPROVED', 'REJECTED', name='project_review_status'), nullable=False, comment='审核状态'),
    sa.Column('business_status', sa.Enum('ONGOING', 'PAUSED', 'COMPLETED', 'ABANDONED', name='project_business_status'), nullable=False, comment='业务状态'),
    sa.Column('created_by', sa.BigInteger(), nullable=False, comment='发起人（联合创始人）'),
    sa.Column('visibility_scope_type', sa.Enum('ALL', 'ROLE_MIN_LEVEL', 'CUSTOM', name='visibility_scope_type'), nullable=False, comment='可见范围类型'),
    sa.Column('visibility_min_role_level', sa.Integer(), nullable=True, comment='最低可见角色等级'),
    sa.Column('visibility_user_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='可见用户ID列表'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resources',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=False, comment='发布者'),
    sa.Column('org_name', sa.String(length=200), nullable=False, comment='所属机构'),
    sa.Column('description', sa.Text(), nullable=False, comment='资源描述'),
    sa.Column('relationship_strength', sa.Integer(), nullable=False, comment='关系强度 1-5'),
    sa.Column('industry', sa.String(length=100), nullable=True, comment='行业'),
    sa.Column('region', sa.String(length=100), nullable=True, comment='地区'),
    sa.Column('note', sa.Text(), nullable=True, comment='备注'),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'EXPIRED', name='resource_status'), nullable=False),
    sa.Column('visibility_scope_type', sa.Enum('ALL', 'ROLE_MIN_LEVEL', 'CUSTOM', name='visibility_scope_type'), nullable=False),
    sa.Column('visibility_min_role_level', sa.Integer(), nullable=True, comment='最低可见角色等级'),
    sa.Column('visibility_user_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_accounts',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=False, comment='当前余额'),
    sa.Column('initial_balance', sa.Numeric(precision=18, scale=2), nullable=False, comment='初始额度'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_availability',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True, comment='备注'),
    sa.Column('visibility_scope_type', sa.Enum('ALL', 'ROLE_MIN_LEVEL', 'CUSTOM', name='visibility_scope_type'), nullable=False),
    sa.Column('visibility_min_role_level', sa.Integer(), nullable=True, comment='最低可见角色等级'),
    sa.Column('visibility_user_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_personal_notes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=False, comment='备注所有者'),
    sa.Column('target_user_id', sa.BigInteger(), nullable=False, comment='被备注的人'),
    sa.Column('content', sa.Text(), nullable=False, comment='备注内容'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_personal_tags',
    sa.Column('owner_user_id', sa.BigInteger(), nullable=False, comment='标签创建者'),
    sa.Column('target_user_id', sa.BigInteger(), nullable=False, comment='被标签的人'),
    sa.Column('tag', sa.String(length=100), nullable=False, comment='标签内容'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('owner_user_id', 'target_user_id', 'tag')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('votes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='投票标题'),
    sa.Column('reason', sa.Text(), nullable=False, comment='投票事由'),
    sa.Column('description', sa.Text(), nullable=True, comment='补充说明'),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='vote_status'), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False, comment='截止时间'),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True, comment='是否匿名'),
    sa.Column('pass_rule', sa.String(length=200), nullable=False, comment='通过标准: 1/3, 1/2, 2/3, 全票, 自定义'),
    sa.Column('allow_abstain', sa.Boolean(), nullable=True, comment='是否开设弃票选项'),
    sa.Column('visibility_scope_type', sa.Enum('ALL', 'ROLE_MIN_LEVEL', 'CUSTOM', name='visibility_scope_type'), nullable=False),
    sa.Column('visibility_min_role_level', sa.Integer(), nullable=True),
    sa.Column('visibility_user_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demands',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False, comment='所属项目'),
    sa.Column('group_id', sa.BigInteger(), nullable=True, comment='同源需求主ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='需求名称'),
    sa.Column('description', sa.Text(), nullable=False, comment='需求内容描述'),
    sa.Column('business_type', sa.String(length=50), nullable=False, comment='业务类型'),
    sa.Column('industry', sa.String(length=100), nullable=True, comment='需求行业'),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'CANCELLED', name='demand_status'), nullable=False),
    sa.Column('expected_reward', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='期望激励形式'),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=False, comment='需求owner'),
    sa.Column('visibility_scope_type', sa.Enum('ALL', 'ROLE_MIN_LEVEL', 'CUSTOM', name='visibility_scope_type'), nullable=False),
    sa.Column('visibility_min_role_level', sa.Integer(), nullable=True),
    sa.Column('visibility_user_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['demands.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dm_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.BigInteger(), nullable=False),
    sa.Column('sender_id', sa.BigInteger(), nullable=False),
    sa.Column('receiver_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['dm_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meetings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='会议主题'),
    sa.Column('description', sa.Text(), nullable=True, comment='简介/议题'),
    sa.Column('meeting_level', sa.Enum('INTERNAL', 'EXTERNAL', name='meeting_level'), nullable=False),
    sa.Column('confidentiality_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='confidentiality_level'), nullable=False),
    sa.Column('related_project_id', sa.BigInteger(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True, comment='地点/线上链接'),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('PLANNING', 'CONFIRMED', 'CANCELLED', 'FINISHED', name='meeting_status'), nullable=False),
    sa.Column('visibility_scope_type', sa.Enum('ALL', 'ROLE_MIN_LEVEL', 'CUSTOM', name='visibility_scope_type'), nullable=False),
    sa.Column('visibility_min_role_level', sa.Integer(), nullable=True),
    sa.Column('visibility_user_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('author_user_id', sa.BigInteger(), nullable=False),
    sa.Column('post_type', sa.Enum('GENERAL', 'PROJECT', 'RESOURCE', 'VOTE', 'ANNOUNCEMENT_REF', name='post_type'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False, comment='文本内容'),
    sa.Column('related_project_id', sa.BigInteger(), nullable=True),
    sa.Column('related_resource_id', sa.BigInteger(), nullable=True),
    sa.Column('related_vote_id', sa.BigInteger(), nullable=True),
    sa.Column('related_announcement_id', sa.BigInteger(), nullable=True),
    sa.Column('visibility_scope_type', sa.Enum('ALL', 'ROLE_MIN_LEVEL', 'CUSTOM', name='visibility_scope_type'), nullable=False),
    sa.Column('visibility_min_role_level', sa.Integer(), nullable=True),
    sa.Column('visibility_user_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_announcement_id'], ['announcements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_resource_id'], ['resources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_vote_id'], ['votes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_join_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('applicant_id', sa.BigInteger(), nullable=False, comment='申请人'),
    sa.Column('desired_role', sa.Enum('OWNER', 'MEMBER', 'RECORDER', name='project_member_role'), nullable=False, comment='申请身份'),
    sa.Column('duty_description', sa.Text(), nullable=False, comment='加入后职责'),
    sa.Column('intended_share_pct', sa.Numeric(precision=10, scale=4), nullable=True, comment='意向获得股份（百分比）'),
    sa.Column('note', sa.Text(), nullable=True, comment='备注'),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='join_request_status'), nullable=False),
    sa.Column('reviewed_by', sa.BigInteger(), nullable=True, comment='审批人'),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True, comment='审批意见'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_members',
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_in_project', sa.Enum('OWNER', 'MEMBER', 'RECORDER', name='project_member_role'), nullable=False, comment='项目中角色'),
    sa.Column('duty_description', sa.Text(), nullable=True, comment='职责说明'),
    sa.Column('join_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('leave_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.create_table('project_news_links',
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('news_id', sa.BigInteger(), nullable=False),
    sa.Column('linked_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['linked_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'news_id')
    )
    op.create_table('project_relations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False, comment='当前项目'),
    sa.Column('related_project_id', sa.BigInteger(), nullable=False, comment='关联项目'),
    sa.Column('relation_desc', sa.Text(), nullable=True, comment='关系说明'),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_shares',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_type', sa.Enum('ORG', 'USER', name='share_owner_type'), nullable=False, comment='持有者类型'),
    sa.Column('owner_id', sa.BigInteger(), nullable=False, comment='持有者ID（ORG时为固定常量0，USER时为用户ID）'),
    sa.Column('percentage', sa.Numeric(precision=10, scale=4), nullable=False, comment='股份比例'),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False, comment='生效时间'),
    sa.Column('note', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_tag_links',
    sa.Column('resource_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['resource_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resource_id', 'tag_id')
    )
    op.create_table('value_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False, comment='金额'),
    sa.Column('currency', sa.String(length=10), nullable=False, comment='币种'),
    sa.Column('description', sa.Text(), nullable=False, comment='描述'),
    sa.Column('related_project_id', sa.BigInteger(), nullable=True),
    sa.Column('record_time', sa.DateTime(timezone=True), nullable=False, comment='计入时间'),
    sa.Column('created_by_admin_id', sa.BigInteger(), nullable=False, comment='录入管理员'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vote_options',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('vote_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vote_id'], ['votes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('mentions', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='被@用户ID列表'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demand_participants',
    sa.Column('demand_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=True, comment='是否为owner'),
    sa.ForeignKeyConstraint(['demand_id'], ['demands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('demand_id', 'user_id')
    )
    op.create_table('demand_responses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('demand_id', sa.BigInteger(), nullable=False),
    sa.Column('responder_id', sa.BigInteger(), nullable=False, comment='响应人'),
    sa.Column('proposal', sa.Text(), nullable=False, comment='响应方案描述'),
    sa.Column('expected_reward', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='响应者意向激励'),
    sa.Column('final_reward', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='最终确认的激励条款'),
    sa.Column('status', sa.Enum('SUBMITTED', 'ACCEPTED_PENDING_USAGE', 'REJECTED', 'ABANDONED', name='demand_response_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['demand_id'], ['demands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responder_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('external_guests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('invited_by_user_id', sa.BigInteger(), nullable=True, comment='谁邀请的'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likes',
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    op.create_table('meeting_minutes',
    sa.Column('meeting_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False, comment='纪要内容'),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='附件列表'),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meeting_id')
    )
    op.create_table('meeting_participants',
    sa.Column('meeting_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('HOST', 'ATTENDEE', 'OPTIONAL', name='participant_role'), nullable=False),
    sa.Column('attendance_status', sa.Enum('INVITED', 'ATTENDING', 'DECLINED', 'NO_SHOW', name='attendance_status'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meeting_id', 'user_id')
    )
    op.create_table('token_transactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('from_user_id', sa.BigInteger(), nullable=True, comment='转出方用户ID'),
    sa.Column('to_user_id', sa.BigInteger(), nullable=True, comment='转入方用户ID'),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False, comment='交易金额（正数）'),
    sa.Column('direction', sa.Enum('TRANSFER', 'ADMIN_GRANT', 'ADMIN_DEDUCT', 'DIVIDEND', name='token_transaction_direction'), nullable=False, comment='交易方向'),
    sa.Column('related_project_id', sa.BigInteger(), nullable=True, comment='关联项目'),
    sa.Column('related_demand_id', sa.BigInteger(), nullable=True, comment='关联需求'),
    sa.Column('status', sa.Enum('PENDING_ADMIN_APPROVAL', 'PENDING_RECEIVER_CONFIRM', 'COMPLETED', 'REJECTED', 'CANCELLED', name='token_transaction_status'), nullable=False, comment='交易状态'),
    sa.Column('reason', sa.Text(), nullable=True, comment='发起理由'),
    sa.Column('admin_comment', sa.Text(), nullable=True, comment='管理员审批意见'),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=False, comment='发起人'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_demand_id'], ['demands.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vote_records',
    sa.Column('vote_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('option_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['vote_options.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vote_id'], ['votes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vote_id', 'user_id')
    )
    op.create_table('demand_response_change_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('demand_id', sa.BigInteger(), nullable=False),
    sa.Column('response_id', sa.BigInteger(), nullable=False),
    sa.Column('change_type', sa.Enum('MODIFY', 'ABANDON', name='change_request_type'), nullable=False, comment='修改/废弃'),
    sa.Column('reason', sa.Text(), nullable=False, comment='修改/废弃原因'),
    sa.Column('new_reward', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='新激励条款'),
    sa.Column('note', sa.Text(), nullable=True, comment='备注'),
    sa.Column('requested_by_user_id', sa.BigInteger(), nullable=False, comment='需求owner发起'),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING_PROVIDER', 'PENDING_ADMIN', 'APPROVED', 'REJECTED', name='change_request_status'), nullable=False),
    sa.Column('provider_decision', sa.String(length=20), nullable=True, comment='ACCEPT/REJECT'),
    sa.Column('provider_decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_user_id', sa.BigInteger(), nullable=True),
    sa.Column('admin_decision', sa.String(length=20), nullable=True, comment='APPROVE/REJECT'),
    sa.Column('admin_decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['demand_id'], ['demands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['response_id'], ['demand_responses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.Enum('PROJECT_CREATED', 'PROJECT_APPROVED', 'PROJECT_REJECTED', 'PROJECT_STATUS_CHANGED', 'PROJECT_MEMBER_JOINED', 'PROJECT_MEMBER_LEFT', 'PROJECT_JOIN_REJECTED', 'SHARE_STRUCTURE_CHANGED', 'DEMAND_PUBLISHED', 'DEMAND_UPDATED', 'DEMAND_CLOSED', 'DEMAND_CANCELLED', 'DEMAND_RESPONDED', 'DEMAND_RESPONSE_REJECTED', 'DEMAND_ACCEPTED', 'DEMAND_RESPONSE_ABANDONED', 'DEMAND_RESPONSE_MODIFIED', 'RESOURCE_USED', 'TOKEN_TRANSFER_COMPLETED', 'TOKEN_DIVIDEND_DISTRIBUTED', 'MEETING_HELD', 'MEETING_MINUTES_ADDED', 'NEWS_LINKED', 'PROJECT_VALUE_RECORDED', 'PROJECT_CLOSED', 'MILESTONE_ADDED', 'NOTE', 'EVENT_CORRECTED', name='project_event_type'), nullable=False, comment='事件类型'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='事件标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='详细描述'),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('related_demand_id', sa.BigInteger(), nullable=True),
    sa.Column('related_response_id', sa.BigInteger(), nullable=True),
    sa.Column('related_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('related_meeting_id', sa.BigInteger(), nullable=True),
    sa.Column('related_news_id', sa.BigInteger(), nullable=True),
    sa.Column('related_value_record_id', sa.BigInteger(), nullable=True),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('share_change_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='通用扩展数据'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_demand_id'], ['demands.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_meeting_id'], ['meetings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_news_id'], ['news.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_response_id'], ['demand_responses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_transaction_id'], ['token_transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_value_record_id'], ['value_records.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_events')
    op.drop_table('demand_response_change_requests')
    op.drop_table('vote_records')
    op.drop_table('token_transactions')
    op.drop_table('meeting_participants')
    op.drop_table('meeting_minutes')
    op.drop_table('likes')
    op.drop_table('external_guests')
    op.drop_table('demand_responses')
    op.drop_table('demand_participants')
    op.drop_table('comments')
    op.drop_table('vote_options')
    op.drop_table('value_records')
    op.drop_table('resource_tag_links')
    op.drop_table('project_shares')
    op.drop_table('project_relations')
    op.drop_table('project_news_links')
    op.drop_table('project_members')
    op.drop_table('project_join_requests')
    op.drop_table('posts')
    op.drop_table('meetings')
    op.drop_table('dm_messages')
    op.drop_table('demands')
    op.drop_table('votes')
    op.drop_table('user_roles')
    op.drop_table('user_personal_tags')
    op.drop_table('user_personal_notes')
    op.drop_table('user_availability')
    op.drop_table('token_accounts')
    op.drop_table('resources')
    op.drop_table('projects')
    op.drop_table('news')
    op.drop_index(op.f('ix_inbox_items_user_id'), table_name='inbox_items')
    op.drop_index(op.f('ix_inbox_items_is_read'), table_name='inbox_items')
    op.drop_table('inbox_items')
    op.drop_table('feedbacks')
    op.drop_table('dm_threads')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_object_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('announcements')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('resource_tags')
    op.drop_table('news_sources')
    # ### end Alembic commands ###

