"""add_project_event_edit_history

Revision ID: 5e53948d724d
Revises: 9f08395fa617
Create Date: 2025-12-15 06:21:39.124245+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e53948d724d'
down_revision: Union[str, None] = '9f08395fa617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_event_edit_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('edited_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('old_title', sa.String(length=500), nullable=True),
    sa.Column('old_description', sa.Text(), nullable=True),
    sa.Column('old_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_title', sa.String(length=500), nullable=True),
    sa.Column('new_description', sa.Text(), nullable=True),
    sa.Column('new_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('edit_reason', sa.Text(), nullable=True, comment='编辑原因'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['edited_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['project_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('project_invitations', 'inviter_id',
               existing_type=sa.BIGINT(),
               comment='邀请人',
               existing_nullable=False)
    op.alter_column('project_invitations', 'invitee_id',
               existing_type=sa.BIGINT(),
               comment='被邀请人',
               existing_nullable=False)
    op.alter_column('project_invitations', 'proposed_role',
               existing_type=postgresql.ENUM('OWNER', 'MEMBER', 'RECORDER', name='project_member_role'),
               comment='建议角色',
               existing_nullable=False,
               existing_server_default=sa.text("'MEMBER'::project_member_role"))
    op.alter_column('project_invitations', 'proposed_duty',
               existing_type=sa.TEXT(),
               comment='建议职责',
               existing_nullable=True)
    op.alter_column('project_invitations', 'proposed_share_pct',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='建议股份（百分比）',
               existing_nullable=True)
    op.alter_column('project_invitations', 'message',
               existing_type=sa.TEXT(),
               comment='邀请留言',
               existing_nullable=True)
    op.alter_column('project_invitations', 'responded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='响应时间',
               existing_nullable=True)
    op.alter_column('project_invitations', 'response_note',
               existing_type=sa.TEXT(),
               comment='响应备注',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_invitations', 'response_note',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='响应备注',
               existing_nullable=True)
    op.alter_column('project_invitations', 'responded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='响应时间',
               existing_nullable=True)
    op.alter_column('project_invitations', 'message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='邀请留言',
               existing_nullable=True)
    op.alter_column('project_invitations', 'proposed_share_pct',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment=None,
               existing_comment='建议股份（百分比）',
               existing_nullable=True)
    op.alter_column('project_invitations', 'proposed_duty',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='建议职责',
               existing_nullable=True)
    op.alter_column('project_invitations', 'proposed_role',
               existing_type=postgresql.ENUM('OWNER', 'MEMBER', 'RECORDER', name='project_member_role'),
               comment=None,
               existing_comment='建议角色',
               existing_nullable=False,
               existing_server_default=sa.text("'MEMBER'::project_member_role"))
    op.alter_column('project_invitations', 'invitee_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='被邀请人',
               existing_nullable=False)
    op.alter_column('project_invitations', 'inviter_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='邀请人',
               existing_nullable=False)
    op.drop_table('project_event_edit_history')
    # ### end Alembic commands ###

